name: Auto-assign Issue + PR

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: mauriciolauffer/.github/.github/workflows/auto-assign.yml@main
