name: NPM Package Publish

on:
  release:
    types: [created]

permissions: read-all

jobs:
  publish:
    permissions:
      id-token: write
    uses: mauriciolauffer/.github/.github/workflows/npm-publish.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
