name: test-x0

on:
  push:
    branches: [ master ]
  pull_request:

permissions: read-all

jobs:
  test-reuse-x0:
    permissions:
      security-events: write
    # uses: mauriciolauffer/.github/workflows/reusable-workflow.yml@main
    # uses: mauriciolauffer/.github/workflow-templates/test.yml@main
    uses: mauriciolauffer/.github/workflows/test.yml@main
