name: test

on:
  push:
    branches: [ master ]
  pull_request:

permissions: read-all

jobs:
  test-reuse:
    # uses: mauriciolauffer/.github/workflows/reusable-workflow.yml@main
    # uses: mauriciolauffer/.github/workflow-templates/test.yml@main
    # uses: mauriciolauffer/.github/workflows/test.yml@main
    uses: mauriciolauffer/.github/.github/workflows/test.yml@main

